import { logger } from "./logger";

export async function sendSlackMessage(text: string): Promise<void> {
  const webhookUrl = process.env.SLACK_WEBHOOK;
  if (!webhookUrl) {
    logger.warn("SLACK_WEBHOOK not set — skipping Slack notification");
    return;
  }

  try {
    const res = await fetch(webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ text }),
    });
    if (!res.ok) {
      logger.warn({ status: res.status }, "Slack webhook returned non-OK status");
    }
  } catch (err) {
    logger.warn({ err }, "Failed to send Slack message");
  }
}

export function formatReportForSlack(report: {
  reportDate: Date | string;
  summary: string;
  stockInsights?: string | null;
  dispatchInsights?: string | null;
  recommendations?: string | null;
  generatedBy?: string | null;
}): string {
  const date = new Date(report.reportDate).toLocaleDateString("en-IN", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const lines: string[] = [
    `*📊 SIHIYAN Daily Operations Report — ${date}*`,
    `_Generated by ${report.generatedBy ?? "Gemini AI"}_`,
    "",
    `*Summary*`,
    report.summary,
  ];

  if (report.stockInsights) {
    lines.push("", `*📦 Stock Insights*`, report.stockInsights);
  }
  if (report.dispatchInsights) {
    lines.push("", `*🚛 Dispatch Insights*`, report.dispatchInsights);
  }
  if (report.recommendations) {
    lines.push("", `*⭐ Recommendations*`, report.recommendations);
  }

  return lines.join("\n");
}
